version: '3'
services:

  service:
    build:
      context: "../roger-service"
      dockerfile: "dist/docker/Dockerfile"
    image: "roger/service:latest"
    expose:
      - 9090
    ports:
      - 9090:9090
    environment:
      PORT: 9090

  dq-details:
    build:
      context: "../roger-dq-details"
      dockerfile: "dist/docker/Dockerfile"
    image: "roger/dq-details:latest"
    expose:
      - 9091
    ports:
      - 9091:9091
    environment:
      PORT: 9091

  operator:
    build:
      context: "../roger-operator"
      dockerfile: "dist/docker/Dockerfile"
    image: "roger/operator:latest"
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      PORT: 9092

  gateway:
    build:
      context: "."
      dockerfile: "dist/docker/Dockerfile"
    image: "roger/gateway:latest"
    depends_on:
      - "service"
    links:
      - "service:service"
      - "dq-details:dq-details"
      - "operator:operator"
    ports:
      - 4000:4000
    command: sh -c "/wait && node server.js"
    environment:
      - WAIT_HOSTS=service:9090,dq-details:9091,operator:9092
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30